import { ArrowRight, Bot, Code, Layers, Zap } from "lucide-react";

export function Features() {
	return (
		<section className="py-32 px-6">
			<div className="max-w-7xl mx-auto">
				<div className="mb-20 text-center max-w-3xl mx-auto animate-fade-up">
					<h2 className="text-4xl md:text-5xl font-semibold text-white tracking-tight font-manrope mb-6">
						The Operating System for <br />
						<span className="text-[#ef233c]">Modern Design Teams</span>
					</h2>
					<p className="text-lg text-zinc-400 font-light">
						Replace your fragmented toolset with one cohesive platform driven by
						AI.
					</p>
				</div>
				<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 h-auto lg:h-[700px]">
					{/* Main card */}
					<div className="lg:col-span-2 lg:row-span-2 group relative overflow-hidden p-8 border border-white/10 bg-gradient-to-b from-zinc-900/50 to-black hover:border-white/20 transition-all rounded-xl">
						<div className="relative z-10 h-full flex flex-col">
							<div className="mb-6 inline-flex p-3 rounded-lg bg-white/5 border border-white/10 text-[#ef233c] w-fit">
								<Bot className="w-6 h-6" />
							</div>
							<h3 className="text-3xl font-semibold text-white font-manrope mb-4 tracking-tight">
								Generative UI Systems
							</h3>
							<p className="text-zinc-400 text-lg leading-relaxed">
								Instantly generate comprehensive design systems from a single
								prompt. Colors, typography, and components are automatically
								created and documented with industry standards in mind.
							</p>
							<div className="mt-auto flex items-center justify-between opacity-0 group-hover:opacity-100 transition-opacity transform translate-y-2 group-hover:translate-y-0">
								<span className="text-xs font-mono text-[#ef233c]">
									EXPLORE FEATURE
								</span>
								<ArrowRight className="w-4 h-4 text-[#ef233c]" />
							</div>
						</div>
						<div
							className="absolute inset-0 opacity-0 group-hover:opacity-10 transition-opacity pointer-events-none"
							style={{
								background:
									"radial-gradient(circle at top right, #ef233c, transparent 70%)",
							}}
						/>
					</div>
					{/* Code Export */}
					<div className="lg:col-span-2 group relative overflow-hidden p-8 border border-white/10 bg-black hover:border-white/20 transition-all rounded-xl">
						<div className="relative z-10 flex flex-col h-full">
							<div className="mb-4 inline-flex p-3 rounded-lg bg-white/5 border border-white/10 text-blue-400 w-fit">
								<Code className="w-6 h-6" />
							</div>
							<h3 className="text-2xl font-semibold text-white font-manrope mb-2">
								Code Export
							</h3>
							<p className="text-zinc-400">
								Production-ready React &amp; Tailwind code, shipped directly to
								your repo with zero friction.
							</p>
						</div>
						<div
							className="absolute inset-0 opacity-0 group-hover:opacity-10 transition-opacity pointer-events-none"
							style={{
								background:
									"radial-gradient(circle at top right, #3b82f6, transparent 70%)",
							}}
						/>
					</div>
					{/* Smart Iteration */}
					<div className="group relative overflow-hidden p-8 border border-white/10 bg-black hover:border-white/20 transition-all rounded-xl">
						<div className="relative z-10">
							<div className="mb-4 inline-flex p-3 rounded-lg bg-white/5 border border-white/10 text-yellow-400 w-fit">
								<Zap className="w-6 h-6" />
							</div>
							<h3 className="text-xl font-semibold text-white font-manrope mb-2">
								Smart Iteration
							</h3>
							<p className="text-sm text-zinc-400">
								A/B test variations generated by AI based on real user data.
							</p>
						</div>
					</div>
					{/* Team Sync */}
					<div className="group relative overflow-hidden p-8 border border-white/10 bg-black hover:border-white/20 transition-all rounded-xl">
						<div className="relative z-10">
							<div className="mb-4 inline-flex p-3 rounded-lg bg-white/5 border border-white/10 text-purple-400 w-fit">
								<Layers className="w-6 h-6" />
							</div>
							<h3 className="text-xl font-semibold text-white font-manrope mb-2">
								Team Sync
							</h3>
							<p className="text-sm text-zinc-400">
								Real-time collaboration with automated version control.
							</p>
						</div>
					</div>
				</div>
			</div>
		</section>
	);
}
